#!/bin/sh 
set -e
TMPDIR=`mktemp -d -t modbustcpXXXXX`
export TMPDIR
export MPID=$$
localhost="127.0.0.1"
trap 'echo signal 15 $MPID $TMPDIR; rm -rf $TMPDIR; kill -15 $MPID; exit 1' 15
trap 'echo signal 2 $MPID $TMPDIR; rm -rf $TMPDIR; kill -2 $MPID; exit 1;' 2
mkdir -p $TMPDIR/modbustcp
mkdir -p e2e/servers/logs
logfile=e2e/servers/logs/modbusTCP_3002.out
# Stable symlink to latest TCP server log
ln -sf "$logfile" e2e/servers/logs/modbusTCP_3002.log

node ./dist/server/runModbusTCPserver.js -d $TMPDIR -c ./e2e/servers/modbustcp.conf/config-dir --busid 0 >>"$logfile" 2>&1 &
MPID=$!  
wait $MPID
