#!/bin/sh 

set -e
TMPDIR=`mktemp -d -t mosquittoXXXXXX`
export TMPDIR
export MPID=$$
trap 'echo signal 15 $MPID $TMPDIR; rm -rf $TMPDIR; kill -15 $MPID; exit 1' 15
trap 'echo signal 2 $MPID $TMPDIR; rm -rf $TMPDIR; kill -2 $MPID; exit 1;' 2

echo homeassistant:homeassistant >$TMPDIR/password.txt 
mosquitto_passwd -U $TMPDIR/password.txt
chmod 700 $TMPDIR/password.txt
sed -e 's|<tmpdir>|'$TMPDIR'|g' <e2e/servers/mosquitto.conf >$TMPDIR/mosquitto.conf
set +e
EXEC=$(which mosquitto)
set -e
if [ -r "/opt/homebrew/sbin/mosquitto" ] 
then
  EXEC=/opt/homebrew/sbin/mosquitto
fi
mkdir -p e2e/servers/logs
logfile=e2e/servers/logs/mosquitto.out
# Stable symlink to latest mosquitto log
ln -sf "$logfile" e2e/servers/logs/mosquitto.log

$EXEC -c $TMPDIR/mosquitto.conf >>"$logfile" 2>&1 &
MPID=$!  

wait $MPID
